### ISSUE TITLE
After Update CLI to 1.18 - npm start not loading file changes

### ISSUE THREAD

**Issue by rajkaran** [strongloop/loopback-next#3337]
## Steps to reproduce
After updating cli version to 1.18.0. I am seeing below error when I executes lb4 controller command
```
The project has dependencies with incompatible versions required by the CLI:
- @loopback/build: ^1.7.1 (cli ^2.0.3)
- @loopback/eslint-config: ^1.1.1 (cli ^2.0.0)
- eslint: ^5.16.0 (cli ^6.0.1)
- eslint-config-prettier: ^4.3.0 (cli ^6.0.0)
```
Addition to this If I continue with existing dependencies I gets:
````
src/controllers/operation-log.controller.ts:85:52 - error TS2345: Argument of type '{ partial: boolean; }' is not assignable to parameter of type 'JsonSchemaOptions'.
  Object literal may only specify known properties, and 'partial' does not exist in type 'JsonSchemaOptions'.

85           schema: getModelSchemaRef(OperationLog, {partial: true}),
                                                      ~~~~~~~~~~~~~

src/controllers/operation-log.controller.ts:119:52 - error TS2345: Argument of type '{ partial: boolean; }' is not assignable to parameter of type 'JsonSchemaOptions'.
  Object literal may only specify known properties, and 'partial' does not exist in type 'JsonSchemaOptions'.

119           schema: getModelSchemaRef(OperationLog, {partial: true}),
                                                       ~~~~~~~~~~~~~

src/controllers/scheduler.controller.ts:85:49 - error TS2345: Argument of type '{ partial: boolean; }' is not assignable to parameter of type 'JsonSchemaOptions'.
  Object literal may only specify known properties, and 'partial' does not exist in type 'JsonSchemaOptions'.

85           schema: getModelSchemaRef(Scheduler, {partial: true}),
                                                   ~~~~~~~~~~~~~

src/controllers/scheduler.controller.ts:119:49 - error TS2345: Argument of type '{ partial: boolean; }' is not assignable to parameter of type 'JsonSchemaOptions'.
  Object literal may only specify known properties, and 'partial' does not exist in type 'JsonSchemaOptions'.

119           schema: getModelSchemaRef(Scheduler, {partial: true}),
                                                    ~~~~~~~~~~~~~


Found 4 errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! ipropel@1.0.0 build: `lb-tsc es2017 --outDir dist`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the ipropel@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/wh-chauhanrajkaran/.npm/_logs/2019-07-11T12_55_52_010Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! ipropel@1.0.0 prestart: `npm run build`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the ipropel@1.0.0 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/wh-chauhanrajkaran/.npm/_logs/2019-07-11T12_55_52_034Z-debug.log

````
Considering it as dependency issue. I create a sample getting-started app and updated my applications dependencies accordingly.
After updating package.json file all errors were gone but now I have .js.map, .d.ts and .js files for all the files I have in project.

## Current Behavior
All of that was fine until I find out that my changes are not taking affect. even console.log doesn't prints out.

## Expected Behavior
Be able to make changes to files and rerun application to see changes

## Additional information
below is my original package.json
````
{
  "name": "ipropel",
  "version": "1.0.0",
  "description": "i-Propel handles printing for patient registration and cisco phone notification for ECG ordered in waitroom.",
  "keywords": [
    "loopback-application",
    "loopback"
  ],
  "main": "index.js",
  "engines": {
    "node": ">=8.9"
  },
  "scripts": {
    "build:apidocs": "lb-apidocs",
    "build": "lb-tsc es2017 --outDir dist",
    "build:watch": "lb-tsc --watch",
    "clean": "lb-clean dist",
    "lint": "npm run prettier:check && npm run eslint",
    "lint:fix": "npm run eslint:fix && npm run prettier:fix",
    "prettier:cli": "lb-prettier \"**/*.ts\" \"**/*.js\"",
    "prettier:check": "npm run prettier:cli -- -l",
    "prettier:fix": "npm run prettier:cli -- --write",
    "eslint": "lb-eslint --report-unused-disable-directives .",
    "eslint:fix": "npm run eslint -- --fix",
    "pretest": "npm run clean && npm run build",
    "test": "lb-mocha --allow-console-logs \"dist/__tests__\"",
    "posttest": "npm run lint",
    "test:dev": "lb-mocha --allow-console-logs dist/__tests__/**/*.js && npm run posttest",
    "docker:build": "docker build -t ipropel .",
    "docker:run": "docker run -p 3000:3000 -d ipropel",
    "migrate": "node ./dist/migrate",
    "prestart": "npm run build",
    "start": "node .",
    "prepublishOnly": "npm run test"
  },
  "repository": {
    "type": "git"
  },
  "author": "",
  "license": "",
  "files": [
    "README.md",
    "index.js",
    "index.d.ts",
    "dist",
    "src",
    "!*/__tests__"
  ],
  "dependencies": {
    "@loopback/boot": "^1.4.0",
    "@loopback/context": "^1.19.0",
    "@loopback/core": "^1.8.1",
    "@loopback/openapi-v3": "^1.6.1",
    "@loopback/repository": "^1.6.1",
    "@loopback/rest": "^1.15.0",
    "@loopback/rest-explorer": "^1.2.1",
    "@loopback/service-proxy": "^1.2.1",
    "loopback-connector-mysql": "^5.4.1",
    "node-schedule": "^1.3.2",
    "nodemailer": "^6.2.1"
  },
  "devDependencies": {
    "@loopback/build": "^1.7.1",
    "@loopback/eslint-config": "^1.1.1",
    "@loopback/testlab": "^1.5.0",
    "@types/node-schedule": "^1.2.3",
    "@types/nodemailer": "^6.2.0",
    "@typescript-eslint/eslint-plugin": "^1.9.0",
    "@typescript-eslint/parser": "^1.9.0",
    "eslint": "^5.16.0",
    "eslint-config-prettier": "^4.3.0",
    "eslint-plugin-eslint-plugin": "^2.1.0",
    "eslint-plugin-mocha": "^5.3.0",
    "typescript": "~3.5.1"
  }
}

````

below is my new package.json
````
{
  "name": "ipropel",
  "version": "1.0.0",
  "description": "i-Propel handles printing for patient registration and cisco phone notification for ECG ordered in waitroom.",
  "keywords": [
    "loopback-application",
    "loopback"
  ],
  "main": "index.js",
  "engines": {
    "node": ">=8.9"
  },
  "scripts": {
    "build": "lb-tsc",
    "build:watch": "lb-tsc --watch",
    "clean": "lb-clean dist *.tsbuildinfo",
    "lint": "npm run prettier:check && npm run eslint",
    "lint:fix": "npm run eslint:fix && npm run prettier:fix",
    "prettier:cli": "lb-prettier \"**/*.ts\" \"**/*.js\"",
    "prettier:check": "npm run prettier:cli -- -l",
    "prettier:fix": "npm run prettier:cli -- --write",
    "eslint": "lb-eslint --report-unused-disable-directives .",
    "eslint:fix": "npm run eslint -- --fix",
    "pretest": "npm run clean && npm run build",
    "test": "lb-mocha --allow-console-logs \"dist/__tests__\"",
    "posttest": "npm run lint",
    "test:dev": "lb-mocha --allow-console-logs dist/__tests__/**/*.js && npm run posttest",
    "docker:build": "docker build -t getting-started .",
    "docker:run": "docker run -p 3000:3000 -d getting-started",
    "migrate": "node ./dist/migrate",
    "prestart": "npm run build",
    "start": "node -r source-map-support/register .",
    "prepublishOnly": "npm run test"
  },
  "repository": {
    "type": "git"
  },
  "author": "",
  "license": "",
  "files": [
    "README.md",
    "index.js",
    "index.d.ts",
    "dist",
    "src",
    "!*/__tests__"
  ],
  "dependencies": {
    "@loopback/boot": "^1.4.4",
    "@loopback/context": "^1.20.2",
    "@loopback/core": "^1.8.5",
    "@loopback/openapi-v3": "^1.7.0",
    "@loopback/repository": "^1.8.2",
    "@loopback/rest": "^1.16.3",
    "@loopback/rest-explorer": "^1.2.5",
    "@loopback/service-proxy": "^1.2.5",
    "loopback-connector-mysql": "^5.4.1",
    "node-schedule": "^1.3.2",
    "nodemailer": "^6.2.1"
  },
  "devDependencies": {
    "@loopback/build": "^2.0.3",
    "source-map-support": "^0.5.12",
    "@loopback/testlab": "^1.6.3",
    "@types/node": "^10.14.10",
    "@typescript-eslint/parser": "^1.11.0",
    "@typescript-eslint/eslint-plugin": "^1.11.0",
    "@loopback/eslint-config": "^2.0.0",
    "eslint": "^6.0.1",
    "eslint-config-prettier": "^6.0.0",
    "eslint-plugin-eslint-plugin": "^2.1.0",
    "eslint-plugin-mocha": "^5.3.0",
    "typescript": "~3.5.2",
    "@types/node-schedule": "^1.2.3",
    "@types/nodemailer": "^6.2.0"
  }
}

````

## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by raymondfeng** [comment]
@rajkaran It's not a good idea to use newer version of CLI against projects scaffolded using an older version. That's why the CLI warned you at the first place.

In your case, you'll have to fix `package.json` and `tsconfig.json` accordingly. Try to generate a new project and compare both files.

**Comment by rajkaran** [comment]
I ended up falling back to 1.17.0 version

**Comment by raymondfeng** [comment]
Not at this moment, but we could possibly save such information in `.yo-rc.json`.

**Comment by bajtos** [comment]
> After updating package.json file all errors were gone but now I have .js.map, .d.ts and .js files for all the files I have in project.

I suspect this is caused by upgrading `@loopback/build` to version 2. See the release notes for instructions on how to upgrade: https://github.com/strongloop/loopback-next/blob/master/packages/build/CHANGELOG.md#200-2019-06-17
